name: cg_device_app
description: "Portable Center of Gravity Computing Device - Weight & Balance System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.2

  # Routing
  go_router: ^14.2.0

  # Fonts
  google_fonts: ^6.2.1

  # Bluetooth
  flutter_blue_plus: ^1.32.12

  # Local Storage
  shared_preferences: ^2.2.3

  # Formatting
  intl: ^0.19.0

  # Animations
  flutter_animate: ^4.5.0

  # Progress / percent indicators
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/HML.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#05111F"
  image: assets/images/APL.png
  image_dark: assets/images/APL.png
  android: true
  ios: false
  web: false
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  background_image: assets/images/APL.png

  android_12:
    color: "#05111F"
    image: assets/images/APL.png
    icon_background_color: "#05111F"
    image_dark: assets/images/APL.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Custom fonts can be added here if not using google_fonts package
